Load Dataset

In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv("StudentsPerformance.csv")
df.head(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [4]:
df.columns
numerical_col = df.select_dtypes(include = "number")
categorical_col = df.select_dtypes(include = "object")
print("Numerical Columns: \n", numerical_col)
print("Categorical Columns: \n", categorical_col)

Numerical Columns:
      math score  reading score  writing score
0            72             72             74
1            69             90             88
2            90             95             93
3            47             57             44
4            76             78             75
..          ...            ...            ...
995          88             99             95
996          62             55             55
997          59             71             65
998          68             78             77
999          77             86             86

[1000 rows x 3 columns]
Categorical Columns:
      gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course
0                      none
1                 completed
2                      none
3                      none
4                      none
..                      ...
995               completed
996                    none
997               completed
998               completed
999                    none

[1000 rows x 5 columns]

# Shape of dataset

In [5]:
df.shape

(1000, 8)

# Description about Data

In [6]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [7]:
df.describe(include="all")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
count,1000,1000,1000,1000,1000,1000.00000,1000.000000,1000.000000
unique,2,5,6,2,2,NaN,NaN,NaN
top,female,group C,some college,standard,none,NaN,NaN,NaN
freq,518,319,226,645,642,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,66.08900,69.169000,68.054000
std,NaN,NaN,NaN,NaN,NaN,15.16308,14.600192,15.195657
min,NaN,NaN,NaN,NaN,NaN,0.00000,17.000000,10.000000
25%,NaN,NaN,NaN,NaN,NaN,57.00000,59.000000,57.750000
50%,NaN,NaN,NaN,NaN,NaN,66.00000,70.000000,69.000000
75%,NaN,NaN,NaN,NaN,NaN,77.00000,79.000000,79.000000
max,NaN,NaN,NaN,NaN,NaN,100.00000,100.000000,100.000000

In [8]:
df.describe(include="object")

,gender,race/ethnicity,parental level of education,lunch,test preparation course
count,1000,1000,1000,1000,1000
unique,2,5,6,2,2
top,female,group C,some college,standard,none
freq,518,319,226,645,642

# Information about data

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

# Check missing values

In [10]:
print("Missing Values: \n", df.isnull().sum())

Missing Values:
 gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

Dataset has no missing values so we insert missing values in the data

# **Insert missing values**

In [11]:
df.loc[4:8,'math score'] = np.nan

In [12]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     5
reading score                  0
writing score                  0
dtype: int64

In [13]:
# df.mask(np.random.rand(*df.shape)<0.05)

In [14]:
print("Missing Values after insertion: \n", df.isnull().sum())

Missing Values after insertion:
 gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     5
reading score                  0
writing score                  0
dtype: int64

# **Remove Missing Values from Data**

In [15]:
# they are filling the values in the columns if mask is used
# df['gender'] = df['gender'].fillna(df['gender'].mode())
# df['race/ethnicity'] =  df['race/ethnicity'].fillna(df['race/ethnicity'].mode())
# df['parental level of education'] = df[parental level of education].fillna(df['parental level of education].mode())
# df['lunch'] = df['lunch'].fillna(df['lunch'].mode())
# df['test preparation course'] = df['test preparation course'].fillna(df['test preparation course'].mode())
# df['math score'] = df['math score'].fillna(df['math score'].mode())
# df['reading score'] = df['reading score'].fillna(df['reading score'].mode())
# df['writing score'] = df['writing score'].fillna(df['writing score'].mode())

In [16]:
# filling numerical missing values
df['math score'] = df['math score'].fillna(df['math score'].median())

In [17]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

# **Duplicate Values**

In [18]:
print("Duplicate Values: ", df.duplicated().sum())

Duplicate Values:  0

# **Outliers**

In [19]:
for col in numerical_col:
  q1 = df[col].quantile(0.25)
  q3 = df[col].quantile(0.75)
  iqr = q3 - q1
  lower = q1 - 1.5*iqr
  upper = q3 + 1.5*iqr
  out = df[ ( df[col] < lower ) | ( df[col] > upper ) ]
  print("Outliers: ",len(out))

Outliers:  8
Outliers:  6
Outliers:  5

# **One-Hot Encoding**

In [20]:
df['gender_female'] = 0
df['gender_male'] = 0
df.loc[df['gender'] == 'female', 'gender_female'] = 1
df.loc[df['gender'] == 'male', 'gender_male'] = 1

df['lunch_standard'] = 0
df['lunch_free_reduced'] = 0
df.loc[df['lunch'] == 'standard', 'lunch_standard'] = 1
df.loc[df['lunch'] == 'free/reduced', 'lunch_free_reduced'] = 1

# Feature Engineering

In [23]:
df['avg_score'] = df[ ['math score' , 'reading score' , 'writing score'] ].mean(axis = 1)
df.head(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,gender_female,gender_male,lunch_standard,lunch_free_reduced,avg_score
0,female,group B,bachelor's degree,standard,none,72.0,72,74,1,0,1,0,72.666667
1,female,group C,some college,standard,completed,69.0,90,88,1,0,1,0,82.333333
2,female,group B,master's degree,standard,none,90.0,95,93,1,0,1,0,92.666667
3,male,group A,associate's degree,free/reduced,none,47.0,57,44,0,1,0,1,49.333333
4,male,group C,some college,standard,none,66.0,78,75,0,1,1,0,73.000000

# Feature Scaling

In [24]:
from sklearn.preprocessing import StandardScaler
scale_cols = [
    "math score",
    "reading score",
    "writing score",
    "avg_score" ]
scaler = StandardScaler()
df[scale_cols] = scaler.fit_transform(df[scale_cols])
print(df[scale_cols].head())

   math score  reading score  writing score  avg_score
0    0.391717       0.193999       0.391492   0.344438
1    0.193212       1.427476       1.313269   1.024081
2    1.582747       1.770109       1.642475   1.750595
3   -1.262492      -0.833899      -1.583744  -1.296078
4   -0.005293       0.605158       0.457333   0.367874